### ISSUE TITLE
Fix null error occurring when the PlayerMoveEvent is passed to the relevant event handler (1.16.5)

### ISSUE THREAD

**Issue by dmccoystephenson** [Dans-Plugins/Wild-Pets#242]
11.03 00:30:15 [Server] Server thread/ERROR Could not pass event PlayerMoveEvent to WildPets v1.4.1
11.03 00:30:15 [Server] INFO org.bukkit.event.EventException: null
11.03 00:30:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1083) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:15 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
11.03 00:30:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
11.03 00:30:16 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by dmccoystephenson** [comment]
Supporting 1.16.5 is not a priority, closing this until this can be reproduced on 1.20.4
